import React, { useState } from 'react'
import "./Projects.css"

function Projects() {
    const [project, setProject] = useState([
        {
            name: "House Price Prediction Using Ml",
            img: "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg",
            link: "https://housepricepredictior.streamlit.app",
            description: "This project aims to predict the price of a house based on various features such as location, number of bedrooms and bathrooms, square footage, year built, and other relevant attributes. Using a machine learning model (e.g., Linear Regression, Random Forest, or XGBoost), the system learns patterns from historical housing data and estimates the market value of new or unseen properties. The goal is to assist buyers, sellers, and real estate agents in making data-driven decisions."
        },
        {
            name: "AI Code Classifier Using Random Forest",
            img: "https://code.visualstudio.com/assets/docs/getstarted/userinterface/sidebyside.png",
            link: "https://ai-code-detector.streamlit.app/",
            description: "This project aims to Detect whether a piece of code was written by a **human** or an **AI model (ChatGPT)** using a machine learning classifier.This project uses a trained **Random Forest** classifier to analyze source code and predict whether it was authored by a human developer or generated by ChatGPT."
        },
        {
            name: "Health and Wellness Dashboard",
            img: "https://shyamfuture.com/wp-content/uploads/2023/08/Health-and-Wellness-APP.jpg",
            link: "https://github.com/Arulmozhivarman-S/HEALTH-AND-WELLNESS", 
            description: "Health and Wellness Application is an interactive platform designed to help users monitor and improve their health. The frontend, built with React.js, provides a dynamic and responsive user interface where users can track their fitness goals, access wellness resources, and manage personal health data.The backend, developed with Spring Boot, handles the business logic, managing user authentication, data processing, and communication between the frontend and the database. It ensures a secure and scalable environment for handling user data.The SQL database serves as the core for storing user information, health records, and wellness plans, ensuring efficient data retrieval and updates."
        },
        {
            img: "https://techexactly.com/wp-content/uploads/2021/04/banner1.jpg",
            name: "Online Medical store",
            link: "https://github.com/Arulmozhivarman-S/ONLINE-MEDICAL-STORE", 
            description: "Online Medical Store is a web-based platform designed to offer a convenient way to purchase healthcare products and medications. The frontend, developed with React.js, delivers a smooth and user-friendly shopping experience, allowing users to browse, search, and order products with ease.The backend, powered by Spring Boot, manages inventory, order processing, and user authentication while ensuring secure transactions and data handling. It also connects the frontend with the database, handles product availability checks, and manages customer orders.The SQL database stores essential data, including product details, customer information, and order histories, ensuring efficient retrieval and updates while maintaining the integrity of sensitive data."
        }
    ]);

    return (
        <div data-aos="fade-up" data-aos-duration="1000">
            <h1 style={{ color: '#624E88' }}>Projects</h1>
            {
                project.map((pro, index) => (
                    <div key={index} style={{ margin: '50px auto' }} className='Projects' data-aos="fade-up" data-aos-duration="1000">
                        <h2>{pro.name}</h2>
                        <div className='Projects-div'>
                            <img className='project-img' style={{ marginTop: '50px', width: '300px', height: '150px' }} src={pro.img} alt={pro.name} />
                            <blockquote><p>{pro.description}</p></blockquote>
                        </div>
                            <a
                                href={pro.link}
                                target="_blank"
                                rel="noopener noreferrer"
                                className="project-link"
                                style={{ display: 'inline-block', marginTop: '10px', color: '#624E88', fontWeight: 'bold' }}
                            >
                                🔗 View Project
                            </a>
                    </div>
                ))
            }
        </div>
    )
}

export default Projects;
